# Generated by Django 3.0.14 on 2022-06-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Id_Food', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_Category', models.IntegerField()),
                ('Food_Name', models.TextField()),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Image', models.TextField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Id_role', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.TextField(max_length=10)),
            ],
        ),
    ]
