# Generated by Django 4.0.4 on 2022-06-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbACCount',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
