# Generated by Django 4.0.5 on 2022-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbOrder',
            fields=[
                ('Id_Order', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_Account', models.TextField()),
                ('Total_Bill', models.TextField()),
                ('Order_Date', models.TextField()),
                ('Phone_Number', models.TextField()),
                ('Address', models.TextField()),
                ('Static', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tbOrderDetail',
            fields=[
                ('Id_Order', models.IntegerField(primary_key=True, serialize=False)),
                ('Id_Food', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
